module.exports = {
	ambulance: 'Ambulance.fbx',
	Bike: 'Bike.obj',
	Bus: 'Bus.fbx',
	ElectricScooter: 'ElectricScooter.fbx',
	FireTruck: 'FireTruck.fbx',
	Hatchback: 'Hatchback.fbx',
	Limousine: 'Limousine.fbx',
	MonsterTruck: 'MonsterTruck.fbx',
	Motorcycle: 'Motorcycle.fbx',
	Muscle: 'Muscle.fbx',
	Muscle2: 'Muscle2.fbx',
	Pickup: 'Pickup.fbx',
	PoliceMuscle: 'PoliceMuscle.fbx',
	PoliceSedan: 'PoliceSedan.fbx',
	PoliceSports: 'PoliceSports.fbx',
	PoliceSUV: 'PoliceSUV.fbx',
	Roadster: 'Roadster.fbx',
	Sedan: 'Sedan.fbx',
	Sports: 'Sports.fbx',
	SUV: 'SUV.fbx',
	Taxi: 'Taxi.fbx',
	Truck: 'Truck.fbx',
	TruckTrailer: 'TruckTrailer.fbx',
	Van: 'Van.fbx'
};
